apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-team-access
  namespace: demo1
rules:
- apiGroups:
  - ""
  resources:
  - deployments
  - pods/log
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  - pods/portforward
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - '*'
