apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-team-access
  namespace: demo1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev-team-access
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: sample_vert
